### ISSUE TITLE
Could not find generator 'super_good:solidus_taxjar:install'.

### ISSUE THREAD

**Issue by diegomichel** [SuperGoodSoft/solidus_taxjar#213]
I wonder if the README is out of date, as explained on this thread: https://github.com/SuperGoodSoft/solidus_taxjar/issues/67

**Comment by forkata** [comment]
Hey @diegomichel 👋🏼 I am curious what discrepancies you are seeing and what version of the library you are running?

We are in preparation for releasing version 1.0 of this gem so the README _should_ reflect the current `master` branch.

**Comment by diegomichel** [comment]
Hey @forkata, on the master branch, it shows the following instructions:

<img width="723" alt="Screenshot 2023-01-25 at 13 30 07" src="https://user-images.githubusercontent.com/848433/214683114-b87c053b-5905-4977-8d0f-6020de46d0d4.png">

But if I try to run the generator it doesn't find it: `bundle exec rails generate super_good:solidus_taxjar:install`

```
Could not find generator 'super_good:solidus_taxjar:install'.
```

Gemfile.lock
```
+ 612     super_good-solidus_taxjar (0.18.2)                                                                                                                                                              
+ 613       solidus_core (>= 2.4.0)                                                                                                                                                                       
+ 614       solidus_support                                                                                                                                                                               
+ 615       taxjar-ruby           
```

Maybe I should point Gemfile to use the master branch on the repo 🤔 

Thanks 🙏

**Comment by forkata** [comment]
Hey @diegomichel! I think that is where the confusion is. The README _should_ reflect the changes in the branch you are on, but we did have an issue previously like you mentioned where it was incorrect for the version of this gem (0.18.2) you are running.

We subsequently [added a generator](https://github.com/SuperGoodSoft/solidus_taxjar/commit/a06d8d50cd99feb45b560c27d1d2581e703aa824) to this extension, but have not released a new version of this gem since then. You would need to reference the library through github in your Gemfile and run agains the master branch to get that.

**Comment by diegomichel** [comment]
Thanks @forkata adding this to the Gemfile makes the generator run (ran into other issues but that's another history lol)

```
gem 'super_good-solidus_taxjar', git: 'https://github.com/SuperGoodSoft/solidus_taxjar'
```

**Comment by forkata** [comment]
Glad that worked out for you. We are going to be doing a 1.0 release in the next couple of weeks which should hopefully remove any confusion over this.
