### ISSUE TITLE
Orders will not be re-synced to TaxJar if first sync fails

### ISSUE THREAD

**Issue by nvandoorn** [SuperGoodSoft/solidus_taxjar#223]
If an order's first sync to TaxJar fails, we may end up calling `replace_transaction` instead of `report_transaction` which results in a no-op. We need a mechanism to retry syncing to TaxJar when the first sync fails.

**Comment by nvandoorn** [comment]
On order_recalculated, we report if the following conditions are met:
- shipped && paid
- reporting enabled
- order.completed_at > reporting_enabled_at
- order has no TaxJar order transaction records

**Comment by Noah-Silvera** [comment]
This PR #244 resolves part of this problem!

But we also need to include the logic @benjaminwil introduced [here](https://github.com/SuperGoodSoft/solidus_taxjar/blob/1fccf8417fe3ffe02d37acbaff40bbd980f397b8/app/controllers/spree/admin/taxjar_transactions_controller.rb#L9) in the `order_recalculated` [event of the subscriber](https://github.com/SuperGoodSoft/solidus_taxjar/blob/1fccf8417fe3ffe02d37acbaff40bbd980f397b8/lib/super_good/solidus_taxjar/spree/reporting_subscriber.rb#L9). This  will allow orders to automatically be correctly reported if their first `report` failed and the order get's recalculated, instead of `replace_transaction` being called as described in this ticket

**Comment by forkata** [comment]
@Noah-Silvera @kchateau and I started on this here - https://github.com/SuperGoodSoft/solidus_taxjar/pull/246

**Comment by forkata** [comment]
@Kendra and I did some more work on trying to address the issue with replacing transactions for orders that failed to be reported initially, but hit a bit of a snag.
Because on `shipment.ship!` the order is recalculated we get both events( `shipment_shipped` _and_ `order_recalculated`). Our initial attempt to fix this was unsuccessful. We may need to check for sync errors and only then allow the transaction to be reported during an `order_recalculated` event as part of the `ReplaceTransactionJob`. We have updated the PR with the work so far and a failing test for the issue we hit - https://github.com/SuperGoodSoft/solidus_taxjar/pull/246
