### ISSUE TITLE
Document creating/updating/deleting transactions and refunds

### ISSUE THREAD

**Issue by octave** [SuperGoodSoft/solidus_taxjar#24]
Hi guys,

It seems like you use Taxjar for calculation but you don't post the transaction to Taxjar? So there is no tracking in Taxjar?

Is there any reason why?

Thanks,

Octave

**Comment by jarednorman** [comment]
This extension does have support for creating transactions and refunds; you can find it [here](https://github.com/SuperGoodSoft/solidus_taxjar/blob/master/lib/super_good/solidus_taxjar/api.rb#L33-L47).

It doesn't do that automatically because these requests should be done in a background job and the extension can't make assumptions about whether an app is using ActiveJob or Sidekiq directly or something else entirely. Instead, you'll need to hook that stuff into the state machine or however you prefer to trigger those calls.

Apologies that this isn't documented! I'm going to hijack this issue as a reminder that this needs documentation.

**Comment by octave** [comment]
Oh sweet! Did see that!

Yeah a little example would be awesome too. We use Sucker punch right now for jobs.

**Comment by aldesantis** [comment]
I'm chiming in here after a Slack discussion with @jarednorman about adding out-of-the-box reporting via ActiveJob directly to this extension. While it seemed a good idea to do it, I realize that we'd have to change the nature of the extension pretty dramatically: currently, the extension is simply a gem rather than a Rails engine.

If we were to provide out-of-the-box reporting, we'd need to turn the extension into a proper Rails engine, add the background jobs and potentially some migrations as well. I'm not against doing that, I just thought I'd check first to make sure it's a direction y'all want to take before I open a PR for doing it.

Providing some documentation would also work, although there are a few gotchas we need to make sure users are aware of:

- Out of the box, there's really no good event to hook into for updating an order. In our apps, we usually end up implementing a custom `order_recalculated` event that is fired after `OrderUpdater` has done its job.
- Users should probably check whether orders are taxable before reporting them.
- Users should make sure they don't try to update orders that were never reported to TaxJar in the first place, or that they only ever upsert transactions instead of creating/updating. This is usually accomplished by adding a couple of DB columns to track whether the transaction/refund was reported to TaxJar.

It would probably be much better to provide a working out-of-the-box implementation and maybe even allow users to customize the logic for scheduling a background job, e.g.:
```ruby
SuperGood::SolidusTaxJar.create_order_scheduler = -> (order) {
  # This would be the default, but users can change it to use their own Sidekiq/Sucker Punch/Resque/etc. job.
  SuperGood::SolidusTaxJar::CreateOrderJob.perform_later(order)
}
```

So, which route do we prefer?

**Comment by Noah-Silvera** [comment]
@aldesantis there is going to be a significant amount of work done in the near future to get this extension [certified with taxjar](https://github.com/SuperGoodSoft/solidus_taxjar/milestone/1). This will require, among other things, an solidus admin taxjar settings panel, which will require a rails engine. Two open PR's #39  and #32 already have work to add a rails engine.

Part of the [certification requirements](https://developers.taxjar.com/integrations/certification-checklist/) is also the ability to turn reporting transactions to Taxjar on/off, and to "Push all US-based transactions to TaxJar". Both of these imply a certified extension should be reporting all taxable transactions to Taxjar, and providing settings around that functionality.

With that in mind, I definitely think we should work towards out of the box reporting! 

I think providing a working out of the box implementation with customization for queuing the background job would make sense!

**Comment by aldesantis** [comment]
@Noah-Silvera sounds good, I'll do some work on this on Friday!

**Comment by octave** [comment]
Happy to test stuff out for you guys!

**Comment by Noah-Silvera** [comment]
We are currently working on an out of the box reporting implementation! Here's the [related ongoing project](https://github.com/SuperGoodSoft/solidus_taxjar/projects/1). 

This implementation will change some of the current API's used to interact with TaxJar to follow the best practices outlined to us by our contacts at TaxJar. In light of that, we are not going to document the current API's, as they will likely be removed to support the out of the box reporting. The out of the box reporting and the new associated API's will be well documented and configurable.
